language: ruby
rvm: 2.6.3
before_install:
- gem update --system
- gem install bundler
install:
- gem install rails
script:
- bundle install
- bundle exec rspec
- ruby request.rb
env:
  global:
    secure: FHnxqS3UTuzJwdjV0ZA6UrL1OXlvz4Iq6zj5pnRTcMdOzY+Hohe0oK010t1kTjFMKu3VPvizSGt5NpVeR29wyyJyfU8/U9BOWhyTP+xM2UtlPVjjz3zYRECwGLDUv04DN8IGGTTFS6SLeNwohQY2gwQeXsQytvu80fLAU5hB4TeksTqLZR0xvi7HnxauHrKdY5r44CAYnO12oJDlWl7SvImhFv0iAevubtwxKHCYP5D4QG0ye+mheMeolW+vu+osgQ+Mc4Mk4kiK2EM8sE5E4h2/1uVaxVPMlswB06S+hM2vbOLmjIilKgLQYqOiPQotwJRX/sGqesRqfEwcKiUfimHaBvOQQf4Mu42n4npiZvvhMJPbTiwYKt0j1c6hPdiGzwjEZvCUjTwB9sL8ZoC92AXxGAUuYaMWjNrcJrJUaWvV7fzQr+PyKA8Qvd0zJThPBoUbbi5WTDFLffMrobPyJeLuAWBIAlnA5ZGGQzZWVu0i/ml5K07nWNro2+XZ1TDfA2Gg2raceqIXunZsnPHXCXHtKWFiI/cPS+jdSxiboUOFjPDS99z5IRjwsj6f0ic5dCf3Kh6KPq6aM6mW3I4n/Hz7+z9yDW0qXkn/k+usaau9q41/vjjFfhXnRyt2goiftrHyS6MtT8LZrbutJIgirX+Il/qIsxsOvBE/VgsuD4U=
